# Eat Safe, Love

## Notebook Set Up

In [44]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [45]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [46]:
# assign the uk_food database to a variable name
uk_food = mongo.uk_food

In [47]:
# review the collections in our database
print(uk_food.list_collection_names())

['establishments']

In [48]:
# assign the collection to a variable
establishments = uk_food.establishments

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [49]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene':20}

# Use count_documents to display the number of documents in the result
print(f'There are {establishments.count_documents(query)} establishments with a hygiene score of 20.')

# Display the first document in the results using pprint
pprint(establishments.find(query)[0])

There are 41 establishments with a hygiene score of 20.
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbee862'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [50]:
# Convert the result to a Pandas DataFrame
hygiene_20 = pd.DataFrame(establishments.find(query))

# Display the number of rows in the DataFrame
print(f'There are {len(hygiene_20)} rows in the DataFrame.')

# Display the first 10 rows of the DataFrame
hygiene_20.head(10)

There are 41 rows in the DataFrame.

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude
0,63c9f97a5a76ed451fbee862,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,63c9f97a5a76ed451fbeebe2,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,63c9f97a5a76ed451fbeeeeb,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,63c9f97a5a76ed451fbef0d9,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,63c9f97a5a76ed451fbef0ea,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
5,63c9f97a5a76ed451fbefa89,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
6,63c9f97a5a76ed451fbefca9,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
7,63c9f97b5a76ed451fbf11e4,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,63c9f97b5a76ed451fbf1616,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,63c9f97b5a76ed451fbf1e27,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [51]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'RatingValue': {'$gte':'4'}, 'LocalAuthorityName': {'$regex': 'London'}}

# Use count_documents to display the number of documents in the result
print(f'There are {establishments.count_documents(query)} establishments in London with a rating value greater than or equal to 4.')

# Display the first document in the results using pprint
pprint(establishments.find(query)[0])

There are 34 establishments in London with a rating value greater than or equal to 4.
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': '4',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97b5a76ed451fbf0277'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [52]:
# Convert the result to a Pandas DataFrame
rating_4 = pd.DataFrame(establishments.find(query))

# Display the number of rows in the DataFrame
print(f'There are {len(rating_4)} rows in the DataFrame.')

# Display the first 10 rows of the DataFrame
rating_4.head(10)

There are 34 rows in the DataFrame.

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude
0,63c9f97b5a76ed451fbf0277,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,"{'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...",FHRS,"{'longitude': 0.508551, 'latitude': 51.369321}",,4627.439468,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,63c9f97b5a76ed451fbf05a2,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.249255999922752, 'latitude': 5...",,4627.873179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
2,63c9f97b5a76ed451fbf10f0,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.561954, 'latitude': 51.543831}",,4631.968418,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
3,63c9f97b5a76ed451fbf1ef0,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.346325, 'latitude': 51.464078}",,4636.847650,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
4,63c9f97b5a76ed451fbf1ef1,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.346336990594864, 'latitude': 5...",,4636.846754,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
5,63c9f97b5a76ed451fbf25f8,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.287555, 'latitude': 51.504071}",,4640.460834,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
6,63c9f97c5a76ed451fbf4704,1252616,0,PI/000035653,Froottree,Other catering premises,7841,Tereza Joanne King George V Lock,Woolwich Manor Way London,Charlton,...,"{'Hygiene': None, 'Structural': None, 'Confide...",FHRS,"{'longitude': 0.0693250000476837, 'latitude': ...",,4648.300000,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
7,63c9f97c5a76ed451fbf4706,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,"{'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...",FHRS,"{'longitude': 0.069286, 'latitude': 51.501121}",,4648.301822,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
8,63c9f97c5a76ed451fbf4adb,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,"{'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.048006, 'latitude': 51.503733}",,4649.173485,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None
9,63c9f97c5a76ed451fbf4ae8,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 0.047966, 'latitude': 51.504112}",,4649.188826,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f...",None,None

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [63]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5

# Save variables for the search radius and Penang Flavours' latitude and longitude
degree_search = 0.01
latitude = 51.490142
longitude = 0.08384

# Create a query where the rating value must be 5, hygiene score must not be empty, 
# and the latitude and longitude must be within 0.01 degree of Penang Flavours' coordiates using the stored values

query = {'RatingValue':'5',
        'geocode.latitude': {'$lte':latitude + degree_search},
        'geocode.latitude': {'$gte':latitude - degree_search},
        'geocode.longitude': {'$lte':longitude + degree_search},
        'geocode.longitude': {'$gte':longitude - degree_search},
        'scores.Hygiene': {'$ne': None}}

# Sort by hygiene score in ascending order so that lowest score (greatest hygiene) are first
sort =  [('scores.Hygiene',1)]

# Set a limit variable equal to 5 to grab the top five establishments
limit = 5

# Use these conditions in a search, convert it into a list, and save it in a variable
search = list(establishments.find(query).sort(sort).limit(limit))

# Print the results
for result in search:  
    pprint(result)

{'AddressLine1': 'The Royal Albion',
 'AddressLine2': 'The Parade',
 'AddressLine3': 'Walton On The Naze',
 'AddressLine4': 'Essex',
 'BusinessName': 'Royal Albion',
 'BusinessType': 'Pub/bar/nightclub',
 'BusinessTypeID': 7843,
 'ChangesByServerID': 0,
 'Distance': 4617.847740736037,
 'FHRSID': 611631,
 'LocalAuthorityBusinessID': '10/00010/FOOD',
 'LocalAuthorityCode': '120',
 'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
 'LocalAuthorityName': 'Tendring',
 'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CO14 8AS',
 'RatingDate': '2019-02-19T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbeeb89'),
 'geocode': {'latitude': 51.84913, 'longitude': 1.273099},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/611631',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'The Shop',
 'AddressLine2': 'Princes Esplanade',
 'AddressLine3': 'Walton On The Naze',
 'AddressLine4': 'Essex',
 'BusinessName': 'Foray Enterprises',
 'BusinessType': 'Takeaway/sandwich shop',
 'BusinessTypeID': 7844,
 'ChangesByServerID': 0,
 'Distance': 4617.847876072012,
 'FHRSID': 1148945,
 'LocalAuthorityBusinessID': '19/00096/FOOD',
 'LocalAuthorityCode': '120',
 'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
 'LocalAuthorityName': 'Tendring',
 'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CO14 8PZ',
 'RatingDate': '2019-06-24T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbeeb8b'),
 'geocode': {'latitude': 51.8520393371582, 'longitude': 1.27618598937988},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1148945',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Eastcliffe Kiosk',
 'AddressLine2': 'East Terrace',
 'AddressLine3': 'Walton On The Naze',
 'AddressLine4': 'Essex',
 'BusinessName': 'The Last Fisherman Cafe',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4617.822272288044,
 'FHRSID': 908226,
 'LocalAuthorityBusinessID': '16/00139/FOOD',
 'LocalAuthorityCode': '120',
 'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
 'LocalAuthorityName': 'Tendring',
 'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CO14 8PX',
 'RatingDate': '2018-05-17T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbeeb7b'),
 'geocode': {'latitude': 51.853985, 'longitude': 1.278971},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/908226',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Cliff Parade',
 'AddressLine2': 'Walton-on-the-Naze',
 'AddressLine3': 'Essex',
 'AddressLine4': '',
 'BusinessName': 'Anchor Lodge',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4617.828603902194,
 'FHRSID': 612189,
 'LocalAuthorityBusinessID': '3254/HS',
 'LocalAuthorityCode': '120',
 'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
 'LocalAuthorityName': 'Tendring',
 'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CO14 8HB',
 'RatingDate': '2019-08-15T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbeeb82'),
 'geocode': {'latitude': 51.856908, 'longitude': 1.2819},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/612189',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Lower Promenade',
 'AddressLine2': 'The Parade',
 'AddressLine3': 'Walton-on-the-Naze',
 'AddressLine4': 'Essex',
 'BusinessName': 'Colonnade Kiosk',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4617.848109377572,
 'FHRSID': 611667,
 'LocalAuthorityBusinessID': '10/00086/FOOD',
 'LocalAuthorityCode': '120',
 'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
 'LocalAuthorityName': 'Tendring',
 'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CO14 8AP',
 'RatingDate': '2019-08-14T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('63c9f97a5a76ed451fbeeb8a'),
 'geocode': {'latitude': 51.848187, 'longitude': 1.272087},
 'latitude': None,
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/611667',
            'rel': 'self'}],
 'longitude': None,
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

In [64]:
# Convert result to Pandas DataFrame
search_df = pd.DataFrame(search)

# Display DataFrame
search_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links,latitude,longitude
0,63c9f97a5a76ed451fbeeb89,611631,0,10/00010/FOOD,Royal Albion,Pub/bar/nightclub,7843,The Royal Albion,The Parade,Walton On The Naze,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.273099, 'latitude': 51.84913}",,4617.847741,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
1,63c9f97a5a76ed451fbeeb8b,1148945,0,19/00096/FOOD,Foray Enterprises,Takeaway/sandwich shop,7844,The Shop,Princes Esplanade,Walton On The Naze,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.27618598937988, 'latitude': 51...",,4617.847876,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
2,63c9f97a5a76ed451fbeeb7b,908226,0,16/00139/FOOD,The Last Fisherman Cafe,Restaurant/Cafe/Canteen,1,Eastcliffe Kiosk,East Terrace,Walton On The Naze,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.278971, 'latitude': 51.853985}",,4617.822272,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
3,63c9f97a5a76ed451fbeeb82,612189,0,3254/HS,Anchor Lodge,Caring Premises,5,Cliff Parade,Walton-on-the-Naze,Essex,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.2819, 'latitude': 51.856908}",,4617.828604,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None
4,63c9f97a5a76ed451fbeeb8a,611667,0,10/00086/FOOD,Colonnade Kiosk,Restaurant/Cafe/Canteen,1,Lower Promenade,The Parade,Walton-on-the-Naze,...,"{'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...",FHRS,"{'longitude': 1.272087, 'latitude': 51.848187}",,4617.848109,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings....",None,None

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [81]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match':{'scores.Hygiene':0}}
# 2. Groups the matches by Local Authority
group_query = {'$group':
                {'_id':'$LocalAuthorityName',
                'count': {'$sum':1}}}
# 3. Sorts the matches from highest to lowest
sort_query = {'$sort': {'count':-1}}

# Put the elements of the pipeline together
pipeline = [match_query, group_query, sort_query]

# Save the reuslts of this pipeline to a list
hygiene_count = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print(f'There are {len(hygiene_count)} documents in this result.')

# Print the first 10 results
pprint(hygiene_count[0:10])

There are 55 documents in this result.
[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [84]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.DataFrame(hygiene_count)
# Display the number of rows in the DataFrame
print(f"There are {len(hygiene_df)} rows in the DataFrame.")
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

There are 55 rows in the DataFrame.

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542